FROM node:20

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npx prisma generate

# Expose port
EXPOSE 8080

# Start the dev server
CMD ["npm", "run", "dev"]
